---
downloads: ~/.ansible-downloads/

configure_dock: yes
configure_terminal: no
configure_osx: no

dockitems_disabled:
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: Slack
    path: /Applications/Slack.app
    pos: 3
  - name: Atom
    path: /Applications/Atom.app
    pos: 4
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 5
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 6

homebrew_installed_packages:
  #- autoconf
  - bash-completion
  - dockutil
  #- doxygen
  #- gettext
  #- gifsicle
  #- git
  - go
  #- gpg
  #- hub
  #- httpie
  #- iperf
  #- libevent
  #- sqlite
  #- mcrypt
  #- nmap
  #- node
  #- nvm
  #- php
  #- ssh-copy-id
  #- cowsay
  #- readline
  #- openssl
  #- pv
  - wget
  #- wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - atom
  - docker
  #- firefox
  - google-chrome
  #- macvim
  #- sequel-pro
  - skitch
  #- slack
  #- sublime-text
  #- transmit
  #- vagrant
  - visual-studio-code

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
