# Configure system for Jellyfin and Kodi
---
- hosts: all
  connection: local

  tasks:
    - name: "create directories"
      file:
        path: "{{ item.dest }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{item.mode}}"
        recurse: yes
        state: directory
      with_items:
        - { dest: '/docker/jellyfin/config', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/kodi', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/tank/Movies', owner: 'crane', group: 'docker',  mode: '0774'}
        - { dest: '/docker/lazylibrarian', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/letsencrypt', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/lidarr', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/ombi', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/portainer', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/qbittorent', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/sabnzbd', owner: 'crane', group: 'docker', mode: '0774'}
        - { dest: '/docker/sonarr', owner: 'crane', group: 'docker', mode: '0774'}
